### ISSUE TITLE
Using the default `guesser` in `Runner` construction will cause bootstrap `go()` to fail

### ISSUE THREAD

**Issue by sweverett** [esheldon/ngmix#225]
I was working on a minimal example to understand mcal fitting with the new API and think I may have run into either a small bug or a small inconsistency in the documentation. I believe the root of it happens here in [`runners.run_fitter()`](https://github.com/esheldon/ngmix/blob/0ce0e94b60b28b06f48f60c90439599e8302e8d9/ngmix/runners.py#L140):
```python
def run_fitter(obs, fitter, guesser=None, ntry=1):
  #...
  if guesser is not None:
      guess = guesser(obs=obs)
      res = fitter.go(obs=obs, guess=guess)
  else:
      res = fitter.go(obs=obs)
```
My simple example didn't set a `guesser`, and most instances in the code it appears as an optional arg. However it fails during the above `fitter.go(obs=obs)` call as it seems to be a required argument in [`fitting.Fitter.go()`]():
```python
def go(self, obs, guess):
  """
  Run leastsq and set the result
  Parameters
  ----------
  obs: Observation, ObsList, or MultiBandObsList
      Observation(s) to fit
  guess: array
      Array of initial parameters for the fit
  """
  ...
```
Maybe I missed something simple, because the examples in `examples/metacal/ ` don't set a guesser either (though they use a `GaussMom` fitter, which makes sense as to why it doesn't need a guess.)

Here is an example that fails, with an input observation either from a MEDS file or from a generated observation using [`examples/metacal/metacal.make_data()`](https://github.com/esheldon/ngmix/blob/0ce0e94b60b28b06f48f60c90439599e8302e8d9/examples/metacal/metacal.py#L199):
```python
psf_model = 'gauss'
gal_model = 'gauss'
shear_step = 0.01

seed = 72396310
rng = np.random.RandomState(seed)

psf_fitter = Fitter(model=psf_model)
fitter = Fitter(model=gal_model)

# the runners run the measurement code on observations
psf_runner = ngmix.runners.PSFRunner(
    fitter=psf_fitter
)
runner = ngmix.runners.Runner(
    fitter=fitter
)

boot = ngmix.metacal.MetacalBootstrapper(
    runner=runner,
    psf_runner=psf_runner,
    step=shear_step,
    rng=rng,
)

# either load in obs from MEDS or create one w/ given `make_data()` func in metacal.py
im_noise = 1e-4
shear = [0.01, 0]
obs = make_data(rng, im_noise, shear)

# will fail here
boot.go(obs)
```
Here is the traceback:
```
Traceback (most recent call last):
  File "/Users/sweveret/repos/superbit-metacal/superbit_lensing/tests/ngmix_v2/issue.py", line 116, in <module>
    main()
  File "/Users/sweveret/repos/superbit-metacal/superbit_lensing/tests/ngmix_v2/issue.py", line 46, in main
    boot.go(obs)
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/metacal/bootstrap.py", line 46, in go
    return metacal_bootstrap(
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/metacal/bootstrap.py", line 113, in metacal_bootstrap
    resdict[key] = bootstrap(
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/bootstrap.py", line 97, in bootstrap
    psf_runner.go(obs=obs)
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/runners.py", line 110, in go
    return run_psf_fitter(
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/runners.py", line 207, in run_psf_fitter
    res = run_fitter(
  File "/Users/sweveret/miniconda3/envs/ngmixv2/lib/python3.10/site-packages/ngmix/runners.py", line 144, in run_fitter
    res = fitter.go(obs=obs)
TypeError: Fitter.go() missing 1 required positional argument: 'guess'
```

**Comment by arunkannawadi** [comment]
I had similar errors when I modified the minimal example to use `AdMomFitter` instead of `GaussMomFitter`. I tried to fix it by passing `guesser` keyword argument, where
`guesser = ngmix.guessers.GMixPSFGuesser(rng, ngauss=1, guess_from_moms=True)`
but was getting `nan`s when running `boot.go(obs)`. Some quantities of interest were
```
'flagstr': 'determinant near zero', 'flux_flags': 16, 'flux_flagstr': 'determinant near zero', 'T_flags': 16, 'T_flagstr': 'determinant near zero',
```

It'd be helpful to specify how to pick various guessers.

**Comment by esheldon** [comment]
Thanks for the reports Spencer and Arun.

**Comment by esheldon** [comment]
I have been on vacation (still am) so I may be slow to respond.

Regarding Spencer's example, we need an example using a maximum likelihood fitter.

However, because the runners we are using duck typing, there will be no foolproof way to detect that a guesser is needed.  We might try to do some introspection to see how many arguments the "go" method requires and emit a message in the runner based upon that.

**Comment by esheldon** [comment]
Arun, your example should have worked.  Can you perhaps post a specific example in another issue?
